# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crisis',
            name='lat',
            field=models.CharField(default='1.3509431', max_length=200),
        ),
        migrations.AddField(
            model_name='crisis',
            name='lng',
            field=models.CharField(default='103.6768071', max_length=200),
        ),
    ]
