# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(default='Burning white Lamborghini at student walk. All passengers are\x0bsafe and are out of the vehicle. Chance of another explosion.'),
        ),
    ]
